title: [CarePath Review]
#description: [Portfolio of CPD activities]
show_downloads: false
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
markdown: kramdown
kramdown:
  parse_block_html: true
